# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/embedded/2018_1_zynq_labs/lab_3/lab_3.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'system_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/embedded/2018_1_zynq_labs/lab_3/lab_3.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/xup/embedded/2018_1_zynq_labs/lab_3/lab_3.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0.xci
# IP: The module: 'system_axi_bram_ctrl_0_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/embedded/2018_1_zynq_labs/lab_3/lab_3.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_bram_0/system_axi_bram_ctrl_0_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
