webtalk_init -webtalk_dir C:\\xup\\embedded\\2015_2_zynq_labs\\lab4\\lab4.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 30 16:09:39 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "79d2ji6avftd238dn63gl415a7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1438297374190" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1438297374190"
webtalk_add_data -client sdk -key uid -value "1438297426688" -context "sdk\\\\bsp/1438297426688"
webtalk_add_data -client sdk -key hwid -value "1438297374190" -context "sdk\\\\bsp/1438297426688"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1438297426688"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1438297426688"
webtalk_add_data -client sdk -key uid -value "1438297428628" -context "sdk\\\\application/1438297428628"
webtalk_add_data -client sdk -key hwid -value "1438297374190" -context "sdk\\\\application/1438297428628"
webtalk_add_data -client sdk -key bspid -value "1438297426688" -context "sdk\\\\application/1438297428628"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1438297428628"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1438297428628"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1438297428628"
webtalk_transmit -clientid 3926643270 -regid "" -xml C:\\xup\\embedded\\2015_2_zynq_labs\\lab4\\lab4.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\xup\\embedded\\2015_2_zynq_labs\\lab4\\lab4.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\xup\\embedded\\2015_2_zynq_labs\\lab4\\lab4.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
